steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install','-DskipTests']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/greeting-app-backend-service', '.']
images: ['gcr.io/$PROJECT_ID/greeting-app-backend-service']
