kind: Service
apiVersion: v1
metadata:
  name: greeting-app-backend-service
spec:
  selector:
     run: greeting-app-backend-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer

