kind: Service
apiVersion: v1
metadata:
  name: greeting-app-backend-service
spec:
  selector:
     run: greeting-app-backend-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
  type: LoadBalancer

